music/urls.py
from music.views import *
from django.urls import path
from django.conf.urls import url

app_name = 'music'


urlpatterns = [
    url(r'^$', IndexView.as_view(), name='index'),
    #music/712
    url(r'^register/$', UserFormView.as_view(), name='register'),

    url(r'^(?P<pk>[0-9]+)/$', DetailView.as_view(), name='detail'),
    # /music/album/add
    url(r'album/add/$', AlbumCreate.as_view(), name='album_add'),

    # /music/album/2/
    url(r'album/(?P<pk>[0-9]+)/$', AlbumUpdate.as_view(), name='album_update'),

    # /music/album/2/delete/
    url(r'album/(?P<pk>[0-9]+)/delete/$', AlbumDelete.as_view(), name='album_delete'),
]

website/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^music/', include('music.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

music/models.py
from django.db import models
from django.urls import reverse

# Create your models here.
class Album(models.Model):
    artist = models.CharField(max_length=250)
    album_title = models.CharField(max_length=250)
    genre = models.CharField(max_length=100)
    album_logo = models.FileField()

    def get_absolute_url(self):
        return reverse('music:detail', kwargs={'pk': self.pk})

    def __str__(self):
        return self.album_title + ' - '+ self.artist

class Song(models.Model):
    album = models.ForeignKey(Album, on_delete=models.CASCADE)
    file_type = models.CharField(max_length=10)
    song_title = models.CharField(max_length=250)
    is_favorite = models.BooleanField(default=False)

    def __str__(self):
        return self.song_title

music/forms.py
from django.contrib.auth.models import User
from django import forms

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'email', 'password']

music/views.py
from django.views import generic
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from .models import *
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.views.generic import View
from .forms import *
from django.urls import reverse_lazy


class IndexView(generic.ListView):
    template_name = 'music/index.html'
    context_object_name = 'all_albums'

    def get_queryset(self):
        return Album.objects.all()

class DetailView(generic.DetailView):
    model = Album
    template_name = 'music/detail.html'

class AlbumCreate(CreateView):
    model = Album
    fields = ['artist', 'album_title', 'genre', 'album_logo']

class AlbumUpdate(UpdateView):
    model = Album
    fields = ['artist', 'album_title', 'genre', 'album_logo']

class AlbumDelete(DeleteView):
    model = Album
    success_url = reverse_lazy('music: index')

class UserFormView(View):
    form_class = UserForm
    template_name = 'music/registration_form.html'

    #display blank form
    def get(self, request):
        form = self.form_class(None)
        return render(request, self.template_name, {'form':form})

    #process form data
    def post(self, request):
        form = self.form_class(request.POST)

        if form.is_valid():
            user = form.save(commit=False)

            #cleaned (normalised) data
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user.set_password(password)
            user.save()

            #returns user objects if credentials are correct
            user = authenticate(username=username, password=password)

            if user is not None:

                if user.is_active:
                    login(request, user)
                    return redirect('music:index')
        return render(request, self.template_name, {form:form})

views.py
from django.shortcuts import render, get_object_or_404
from .models import *
from django.http import HttpResponse,Http404

# Create your views here.
def index(request):
    all_albums = Album.objects.all()

    context = {
        'all_albums': all_albums,
    }
    return render(request, 'music/index.html', context)

def detail(request, album_id):

    album = get_object_or_404(Album, pk=album_id)
    context = {
        'album': album,
    }
    return render(request, 'music/detail.html', context)
def favorite(request, album_id):
    album = get_object_or_404(Album, pk=album_id)
    context = {
        'album': album,
    }
    try:
        selected_song = album.song_set.get(pk=request.POST['song'])
        print("________________________________")
        print(selected_song)
    except(KeyError, Song.DoesNotExist):
        return render(request, 'music/detail.html', {'album': album,
                                                     'error_message': "you did not enter valid song"})
    else:
        print(selected_song)
        selected_song.is_favorite = True
        selected_song.save()
    return render(request, 'music/detail.html', context)

music/templates/music/album_form.html
{% extends 'music/base.html' %}
{% block title %}Add a New Album{% endblock %}
{% block albums_active %}active{% endblock %}

{% block body %}
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-12 col-md-7">
            <div class="panel panel-default">
                <div class="panel-body">

<form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {% include 'music/form-template.html' %}
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <button type="submit" class="btn btn-success">Submit</button>
        </div>
    </div>
</form>

                </div>
        </div>
        </div>
    </div>
</div>
{% endblock %}

music/templates/music/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Wii{% endblock %}</title>
    {% load staticfiles %}
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
<link rel="stylesheet" type="text/css" href="{% static 'music/style.css' %}" />
<link href="https://fonts.googleapis.com/css?family=Lobster" rel="stylesheet">
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">

</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-secondary">
  <a class="navbar-brand" href="{% url 'music:index' %}">WII</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'music:index' %}"><span><i class="fas fa-music"></i></span>&nbsp; Albums </a>
      </li>
      <li class="nav-item ">
        <a class="nav-link" href="#"><span><i class="fas fa-compact-disc"></i></span>&nbsp; Song</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Artists
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="#">Taylor Swift</a>
          <a class="dropdown-item" href="#">Kanye</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Eminem</a>
        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled" href="#">Disabled</a>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0" role="search" method="get" action="#">
      <input class="form-control mr-sm-2" name="q" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit"><i class="fas fa-search"></i></button>
    </form>

      <ul class="nav navbar-nav navbar-right">
          <li class="nav-item active">
        <a class="nav-link" href="{% url 'music:album_add' %}"><span><i class="far fa-plus-square"></i></span>&nbsp; Add Album </a>
      </li>
      <li class="nav-item ">
        <a class="nav-link" href="#"><span><i class="fas fa-sign-out-alt"></i></span>&nbsp; Logout</a>
      </li>
      </ul>
  </div>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

music/templates/music/detail.html
{% extends 'music/base.html' %}

<title>{% block title %}Album details{% endblock %}</title>
{% block body %}
<body>

<a href="{% url 'music:detail' album.id %}">
<img class="img-responsive" src="{{ album.album_logo.url }}">
</a>

<h1>{{ album.album_title }}</h1>
<h3>{{ artist }}</h3>

<ul>
    {% for song in album.song_set.all %}
    <li>{{ song.song_title }} - {{ song.file_type }}</li>
    {% endfor %}
</ul>

{% if error_message %}
    <p><strong>{{ error_message }}</strong></p>
{% endif %}


</body>
</html>
{% endblock %}

music/templates/music/form-template.html
{% for field in form %}
<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <span class="text-danger small">{{ field.errors }}</span>
    </div>
    <label class="control-label col-sm-2">{{ field.label_tag }}</label>
    <div class="col-sm-10">{{ field }}</div>
</div>
{% endfor %}

music/templates/music/index.html
{% extends 'music/base.html' %}
 <title>{% block title %}Album index{% endblock %}</title>
{% block body %}
    {% if all_albums %}
        <ul style="border-color:black;, border-width=30px;">
            {% for album in all_albums %}
            <!--Details-->
            <div class="col-sm-4 col-lg-2">
                <div class="thumbnail">
            <li><a href="{% url 'music:detail' album.id %}">
                <img src="{{ album.album_logo.url }}" class="img-responsive img-thumbnail"></a></li>

            <!--Delete-->
            <form action="{% url 'music:album_delete' album.id %}" method="post" style="display: inline;">
                {% csrf_token %}
                <input type="hidden" name="album_id" valuse="{{ album.id }}"/>
                <button type="submit" class="btn btn-danger btn-sm">
                    <i class="fas fa-trash"></i>
                </button>
            </form>

            <a class="btn btn-outline-info" href="{% url 'music:album_update' album.id %}">{{ album.album_title }}</a>
</div>
</div>
            {% endfor %}
        </ul>
    {% else %}
        <h2>No Albums</h2>
    {% endif %}

{% endblock %}

music/templates/music/registration_form.html
{% extends 'music/base.html' %}
{% block title %}Register{% endblock %}


{% block body %}
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-12 col-md-7">
            <div class="panel panel-default">
                <div class="panel-body">

<form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {% include 'music/form-template.html' %}
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <button type="submit" class="btn btn-success">Submit</button>
        </div>
    </div>
</form>

                </div>
        </div>
        </div>
    </div>
</div>
{% endblock %}